{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "k8s-demo.fullname" . }}
  labels:
    app: {{ template "k8s-demo.name" . }}
    chart: {{ template "k8s-demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.capacity }}
      
{{- if .Values.persistence.storageClass }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- if .Values.persistence.VolumeName }}
  volumeName: "{{ .Values.persistence.VolumeName }}"
{{- end }}
{{- end }}