apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8s-demo.fullname" . }}
  labels:
    app: {{ template "k8s-demo.name" . }}
    chart: {{ template "k8s-demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  # nodePort: The port on the node where external traffic will come in on
  # port: The port of this service
  # targetPort: The target port on the pod(s) to forward traffic to
    - name: {{ .Values.service.port.name }}
      port: {{ .Values.service.port.port }}
      nodePort: {{ .Values.service.port.nodePort }}
      targetPort: {{ .Values.service.port.targetPort }}
  selector:
    app: {{ template "k8s-demo.name" . }}
    release: {{ .Release.Name }}
