{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "k8s-demo.name" . }}-serviceaccount
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "k8s-demo.name" . }}
    chart: {{ template "k8s-demo.chart" . }}
    release: "{{ .Release.Name }}"
{{- end -}}